# Generated by Django 3.1.5 on 2021-01-25 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220, verbose_name='Заголовок')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image', verbose_name='Изображение')),
                ('weight', models.IntegerField(verbose_name='Вес')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
        ),
    ]
