# Generated by Django 3.1.5 on 2021-01-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='image')),
                ('weight', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=4, max_digits=100)),
            ],
        ),
    ]
