# Generated by Django 3.1.5 on 2021-01-31 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Отзыв')),
                ('created_at', models.DateField(verbose_name='Дата создания')),
                ('published_at', models.DateField(verbose_name='Дата публикации')),
                ('status', models.CharField(choices=[('MOD', 'На модерации'), ('PUB', 'Опубликован'), ('REJ', 'Отклонен')], default='MOD', max_length=3, verbose_name='Статус публикации')),
            ],
        ),
    ]
