# Generated by Django 3.1.5 on 2021-03-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='review',
            name='published_at',
            field=models.DateField(blank=True, null=True, verbose_name='Дата публикации'),
        ),
    ]
