# Generated by Django 3.1.5 on 2021-03-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
    ]
